//
//  allChainsEnum.swift
//  DefiLlama
//
//  Created by Hunter Diamond on 9/9/23.
//

import Foundation

enum AllChains: String, CaseIterable, Codable {
    case acala = "Acala"

    case arbitrum = "Arbitrum"
    case zkSyncEra = "zkSync Era"
    case base = "Base"
    case ethereum = "Ethereum"
    case bsc = "BSC"
    case polygon = "Polygon"
    case kcc = "KCC"
    case fantom = "Fantom"
    case kava = "Kava"
    case mantle = "Mantle"
    case avalanche = "Avalanche"
    case telos = "Telos"
    case gnosis = "Gnosis"
    case polygonZkEVM = "Polygon zkEVM"
    case concordium = "Concordium"
    case optimism = "Optimism"
    case cardano = "Cardano"
    case conflux = "Conflux"

    case aurora = "Aurora"
    case boba = "Boba"
    case elastos = "Elastos"
    case oktChain = "OKTChain"
    case fuse = "Fuse"
    case iotex = "IoTeX"
    case cronos = "Cronos"
    case evmos = "Evmos"
    case harmony = "Harmony"
    case moonbeam = "Moonbeam"
    case moonriver = "Moonriver"
    case hydra = "Hydra"
    case linea = "Linea"
    case bittorrent = "Bittorrent"
    case solana = "Solana"
    case metis = "Metis"
    case cosmosHub = "CosmosHub"
    case algorand = "Algorand"
    case tezos = "Tezos"
    case dogechain = "Dogechain"
    case neon = "Neon"
    case celo = "Celo"
    case arbitrumNova = "Arbitrum Nova"
    case thunderCore = "ThunderCore"
    case aptos = "Aptos"
    case near = "NEAR"
    case smartBCH = "SmartBCH"
    case bitcoin = "Bitcoin"
    case canto = "Canto"
    case doge = "Doge"
    case neo = "Neo"
    case phantasma = "Phantasma"
    case juno = "Juno"
    case litecoin = "Litecoin"
    case opBnb = "Op_Bnb"
    case klaytn = "Klaytn"
    case osmosis = "Osmosis"
    case stargaze = "Stargaze"
    case terraClassic = "Terra Classic"
    case injective = "Injective"
    case umee = "Umee"
    case dfk = "DFK"
    case tron = "Tron"
    case onus = "Onus"
    case waves = "Waves"
    case defichain = "Defichain"
    case savannah = "Savannah <3"
    case mixin = "Mixin"
    case filecoin = "Filecoin"
    case multiversX = "MultiversX"
    case stride = "Stride"
    case hedera = "Hedera"
    case heco = "Heco"
    case kusama = "Kusama"
    case polkadot = "Polkadot"
    case astar = "Astar"
    case bifrost = "Bifrost"
    case bitcoincash = "Bitcoincash"
    case bobaBnb = "Boba_Bnb"
    case carbon = "Carbon"
    case cosmos = "Cosmos"
    case cube = "Cube"
    case karura = "Karura"
    case kucoin = "Kucoin"
    case libre = "Libre"
    case milkomedaA1 = "Milkomeda A1"
    case milkomedaC1 = "Milkomeda C1"
    case nuls = "Nuls"
    case oasis = "Oasis"
    case obyte = "Obyte"
    case ontology = "Ontology"
    case reichain = "Reichain"
    case rootstock = "Rootstock"
    case vechain = "Vechain"
}

enum BigTenChains: String, CaseIterable {
    case all = "All"
    case ethereum = "Ethereum"
    case tron = "Tron"
    case bsc = "BSC"
    case arbitrum = "Arbitrum"
    case polygon = "Polygon"
    case optimism = "Optimism"
    case avalanche = "Avalanche"
    case base = "Base"
    case mixin = "Mixin"
    case solana = "Solana"
    case bitcoin = "Bitcoin"
    
}
