//
//  allChainsEnum.swift
//  DefiLlama
//
//  Created by Hunter Diamond on 9/9/23.
//

import Foundation

enum AllChains: String, CaseIterable {
    case arbitrum = "Arbitrum"
    case zkSyncEra = "zkSync Era"
    case base = "Base"
    case ethereum = "Ethereum"
    case bsc = "BSC"
    case polygon = "Polygon"
    case kcc = "KCC"
    case fantom = "Fantom"
    case kava = "Kava"
    case mantle = "Mantle"
    case avalanche = "Avalanche"
    case telos = "Telos"
    case gnosis = "Gnosis"
    case polygonZkEVM = "Polygon zkEVM"
    case concordium = "Concordium"
    case optimism = "Optimism"
    case cardano = "Cardano"
    case aurora = "Aurora"
    case boba = "Boba"
    case elastos = "Elastos"
    case oktChain = "OKTChain"
    case fuse = "Fuse"
    case iotex = "IoTeX"
    case cronos = "Cronos"
    case evmos = "Evmos"
    case harmony = "Harmony"
    case moonbeam = "Moonbeam"
    case moonriver = "Moonriver"
    case hydra = "Hydra"
    case linea = "Linea"
    case bittorrent = "Bittorrent"
    case solana = "Solana"
    case metis = "Metis"
    case cosmosHub = "CosmosHub"
    case algorand = "Algorand"
    case tezos = "Tezos"
    case dogechain = "Dogechain"
    case neon = "Neon"
    case celo = "Celo"
    case arbitrumNova = "Arbitrum Nova"
    case thunderCore = "ThunderCore"
    case aptos = "Aptos"
    case near = "Near"
    case smartBCH = "smartBCH"
    case bitcoin = "Bitcoin"
    case canto = "Canto"
    case doge = "Doge"
    case neo = "NEO"
    case phantasma = "Phantasma"
    case juno = "Juno"
    case litecoin = "Litecoin"
    case opBnb = "Op_Bnb"
    case klaytn = "Klaytn"
    case osmosis = "Osmosis"
    case stargaze = "Stargaze"
    case terraClassic = "Terra Classic"
    case injective = "Injective"
    case umee = "Umee"
    case dfk = "DFK"
    case tron = "Tron"
    case onus = "Onus"
    case waves = "Waves"
}
